---
nycdb_packages:
  - sudo
  - wget
  - curl
  - zip
  - unzip
  - bzip2
  - git
  - tmux
  - mosh
  - htop
  - build-essential
  - python3
  - python3-pip
  - python3-dev
  - python3-venv
  - python3-setuptools

postgres_apt_repository: "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main"

postgres_packages:
  - postgresql-12
  - postgresql-client-12
  - postgresql-contrib-12
  - libpq-dev
