---
- name: Install required packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - pandoc
      - xz-utils
      - unzip

- name: Setup postgres users
  become: yes
  import_tasks: psql.yml
  tags: psql

- name: Create api group
  group:
    name: api
    state: present

- name: Create api user
  user:
    name: api
    group: api
    shell: /bin/false

- name: Download postgrest binary
  unarchive:
    src: "{{ postgrest_release_url }}"
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
    remote_src: yes
    creates: /usr/local/bin/postgrest
  tags: postgrest

- name: Create postgres.conf file
  template:
    src: postgrest.conf.j2
    dest: /home/api/postgrest.conf
    owner: api
    group: api
    mode: 0644
  tags: postgrest

- name: Install nycdb systemd unit file
  template:
    src: nycdb.service.j2
    dest: /etc/systemd/system/nycdb.service
  tags: postgrest

- name: Start nycdb service
  systemd:
    name: nycdb
    daemon_reload: yes
  tags: postgrest

- name: Create /var/www/nycdb
  file:
    path: /var/www/nycdb
    state: directory
    owner: nycdb
    group: nycdb
    mode: 0755
  tags: docs


- name: Build docs
  become_user: "{{ nycdb_user }}"
  vars:
    ansible_ssh_pipelining: true
  make:
    chdir: /srv/nyc-db/server
    target: index.html

- name: copy index.html to /var/www/nycdb
  copy:
    src: /srv/nyc-db/server/index.html
    dest: /var/www/nycdb/index.html
    remote_src: yes
    owner: nycdb
    group: nycdb
    mode: 0644
